name: flutter_bmflocation
description: BaiduMapLocation plugin for flutter. This plugin provides a cross-platform (iOS, Android) API to request location.
version: 3.2.0
homepage: https://lbsyun.baidu.com/index.php?title=flutter/loc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_baidu_mapapi_base: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.baidu.flutter_bmflocation
        pluginClass: FlutterBmflocationPlugin
      ios:
        pluginClass: FlutterBmflocationPlugin